language: rust

env: TYPE=default RUST_BACKTRACE=1

rust:
  - "1.42.0"
  - stable
  - nightly

os:
  - linux
  - osx

 before_install:
   - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc@8 > /dev/null; fi

 addons:
   apt:
     packages:
       - gfortran

sudo: false

# cargo test --doc with shared lib is broken https://github.com/rust-lang/cargo/issues/8531#ref-pullrequest-719728963
script:
  - cargo test -v
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cargo test -v --features blas --features accelerate; fi
  - cargo test --lib -v --features blas --features intel-mkl
  - cargo test --lib -v --features blas --features openblas
