language: rust

env: TYPE=default RUST_BACKTRACE=1

rust:
  - "1.42.0"
  - stable
  - nightly

jobs:
  include:
    - os: linux
    - os: osx
      osx_image: xcode12.2

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc@8 > /dev/null; fi

addons:
  apt:
    packages:
      - gfortran

sudo: false

cache: cargo

install:
  - cargo build -v

script:
  - cargo test -v
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cargo test -v --features blas --features accelerate; fi
  - cargo test -v --features blas --features intel-mkl
  - gfortran --version
  - cargo test -v --features blas --features openblas