language: rust

env: TYPE=default RUST_BACKTRACE=1

rust:
  - "1.38.0"
  - stable
  - nightly

jobs:
  include:
    - os: linux
    - os: osx
      osx_image: xcode12.2

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc8 > /dev/null; fi

addons:
  apt:
    packages:
      - gfortran

sudo: false

cache: cargo

install:
  - cargo build -v

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cargo test -v &&
    cargo test -v --features blas --features accelerate &&
    cargo test -v --features blas --features intel-mkl &&
    cargo test -v --features blas --features openblas ;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo test -v &&
    cargo test -v --features blas --features intel-mkl &&
    cargo test -v --features blas --features openblas ;fi
