language: rust

env: TYPE=default RUST_BACKTRACE=1

rust:
  - "1.42.0"
  - "1.48.0"
  - stable
  - nightly

os:
  - linux
  - osx

# before_install:
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc@8 > /dev/null; fi

# addons:
  # apt:
    # packages:
      # - gfortran

sudo: false

script:
#  - cargo test -v
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cargo test -v --features blas --features accelerate; fi
  - ls /home/travis/build/raskr/rust-autograd/target/debug/build/intel-mkl-src-*/out
  - cargo test -v --features blas --features intel-mkl
  # - gfortran --version
