language: rust

env: TYPE=default RUST_BACKTRACE=1

rust:
  - "1.38.0"
  - stable
  - nightly

os:
  - linux
  - osx

sudo: false

cache: cargo

install:
  - cargo build -v

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cargo test -v &&
    cargo test -v --features blas --feature accelerate &&
    cargo test -v --features blas --feature intel-mkl &&
    cargo test -v --features blas --feature openblas ;fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo test -v &&
    cargo test -v --features blas --feature intel-mkl &&
    cargo test -v --features blas --feature openblas ;fi
